import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="h-20 p-8 sm:p-20 bg-white rounded-lg shadow-lg text-gray-800 mt-8 mb-8"> Header placeholder</header>
        {children}
        <footer className="h-20 p-8 sm:p-20 bg-white rounded-lg shadow-lg text-gray-800 mt-8 mb-8"> Footer placeholder</footer>
      </body>
    </html>
  );
}
